services:
    database-server:
      image: "postgres:14.2"
      restart: unless-stopped
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "ChAnG3Me"
      volumes:
        - ./docker-volumes/postgres:/var/lib/postgresql/data
      ports:
        - 127.0.0.1:5002:5432